### ISSUE TITLE
Templates: Update template using Andada

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10829]
## Task Description

This is a follow-up to #10819, e6dc2e95961688d3935a9849587ae50426b0c0f2, and #10828

I realized that the “Food & Stuff” template uses the “Andada” font which was superseded by “Andada Pro” a while back.

We should update the template accordingly. Since the font only slightly changed, it should be a relatively simple update. It can be even done using a data migration so that we don't cause "Missing font" dialog to appear for lots of users.

Template to change: https://github.com/GoogleForCreators/web-stories-wp/blob/4cbc5bc0759e01653fed9e5c33fed3d55b59bc62/packages/templates/src/raw/food-and-stuff/template.json

<table>
<tr>
	<td>Before
	<td>After
<tr>
	<td><img src="https://user-images.githubusercontent.com/841956/157219361-37d0b7e6-bccb-4628-8ae2-6259a8cd83c0.png" alt="before" />
	<td><img src="https://user-images.githubusercontent.com/841956/157219358-f8cd8f39-dd1e-4b6f-8dc8-b7ec019bb92b.png" alt="after" />
</table>

### Acceptance Criteria

* [ ] Add a new data migration to replace Andada font with Andada Pro, including font metrics. (Right now the metrics seem to be missing from the template)
* [ ] Add tests for data migration
* [ ] Run new data migration using `npm run workflow:migrate`. This will automatically update the Food & Stuff template.
* [ ] Unskip test from #10830

**Comment by spacedmonkey** [comment]
> including font metrics. (Right now the metrics seem to be missing from the template)

How does one add these fonts metrics. What they do and how are these values generated?

**Comment by swissspidy** [comment]
You don't need to generate them. Just copy the whole font information for Andada Pro from `fonts.json` in this repo.

**Comment by spacedmonkey** [comment]
> Just copy the whole font information for Andada Pro from fonts.json in this repo.

Manually copy them to templates or as part of the migration?

**Comment by swissspidy** [comment]
As part of the migration.

As per the Acceptance Criteria above, the migration will then automatically update the template (`npm run workflow:migrate`). This way we feed 2 birds with one scone.

**Comment by spacedmonkey** [comment]
> As part of the migration.

Okay, should these values be hardcoded or should the values be loaded from the fonts package. I don't love making the fonts package a dependency.

**Comment by swissspidy** [comment]
Hardcoded/copied over. No fonts package dependency.
