### ISSUE TITLE
ESLint: Disable `react/jsx-no-target-blank` rule

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10827]
## Task Description

The `react/jsx-no-target-blank` rule is obsolete, since all the browsers we currently support automatically imply `rel="noopener"` when using `target="_blank`.

Also, `rel="noreferrer"` was only needed originally for browser that didn't support `noopener`.

### Acceptance Criteria

* [ ] `react/jsx-no-target-blank` ESLint rule is disabled
* [ ] No `rel="noreferrer"` `rel="noopener"` anymore in the JS code base
* [ ] Remove `noopener` and `noreferrer` from `PluginRowMeta` as well

**Comment by swissspidy** [comment]
As per my last comment on #10887, moving this to backlog again for now.
