### ISSUE TITLE
Shopping: Support custom CTA text

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11309]
## Feature Description

As of very recently, the default CTA text for the shopping attachment ("Shop now") can be customized, just like for regular page attachments / outlinks.

See https://github.com/ampproject/amphtml/issues/38080

We now want to add support for this in the editor as well in the `PageAttachmentPanel`.

**To-do:**

* [ ] Add `cta-text` attribute to `amp-story-shopping-attachment` allowlist in `KSES`
	* [ ] Add test for it
* [ ] Add CTA text input field to `PageAttachmentPanel`
	* [ ] Maybe refactor this component to split it into two, as it is quite large already
	* [ ] Good time to add some JS unit tests for it as well
* [ ] Update `ProductOutput` component to add `cta-text` attribute 
	* [ ] Add test for it

## Additional Context

Existing CTA text input field for regular page attachments:

<img width="351" alt="Screenshot 2022-04-19 at 16 58 06" src="https://user-images.githubusercontent.com/841956/164033859-84f66744-8d4c-4299-b417-440d5a0904e1.png">

**Comment by spacedmonkey** [comment]
Seems like the last update was nearly 2 months ago. https://github.com/ampproject/amp-wp/commit/4076e7c91b5551e95aefc1d0535435cf4f72c55d

**Comment by westonruter** [comment]
Yeah, it was last updated in https://github.com/ampproject/amp-wp/pull/6956 on March 3. How urgently is this needed?

**Comment by swissspidy** [comment]
Not urgent. We can patch this ourselves in the meantime. Would be nice to resolve this in May or so though.

**Comment by westonruter** [comment]
I've opened a PR with the update: https://github.com/ampproject/amp-wp/pull/7078
