### ISSUE TITLE
WordPress 6.2 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#13043]
## Task Description

RC 1 is due out on March 7, with stable release on March 28. See https://make.wordpress.org/core/6-2/

**Previously:**

* #12223

**Before release of WordPress 6.2:**

* [x] Manual testing against trunk and Beta releases
* [x] Run E2E tests against 6.2 RC once published
* [x] Update staging environments to use 6.2 RC
* [x] Bump `Tested up to` in `readme.txt`

**After release of WordPress 6.2:**

* [x] Update `php-stubs/wordpress-stubs` (via `composer update`)
* [x] Update `sniccowp/php-scoper-wordpress-excludes`
