### ISSUE TITLE
WordPress 6.3 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#13259]
## Task Description

According to https://make.wordpress.org/core/2023/04/14/wordpress-6-3-planning-proposal-call-for-volunteers/, the first RC will be out in July, with general release in early August.

**Previously:**

* #13043

**Before release of WordPress 6.2:**

* [x] Manual testing against trunk/Beta/RC releases
* [x] Run E2E tests against 6.3 RC once published
* [x] Update staging environments to use 6.3 RC
* [x] Bump `Tested up to` in `readme.txt`

**After release of WordPress 6.3:**

* [ ] Update `php-stubs/wordpress-stubs` (via `composer update php-stubs/wordpress-stubs`)
* [ ] Update `sniccowp/php-scoper-wordpress-excludes`

**Comment by swissspidy** [comment]
`php-stubs/wordpress-tests-stubs` is already a painful upgrade, so let's skip that one for now.

**Comment by swissspidy** [comment]
There's a new `item_trashed` post type label we should add

**Comment by swissspidy** [comment]
Let's also bump the AMP plugin version now that 2.4.2 is out
