### ISSUE TITLE
Bump WP version requirement to 6.2+

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#13424]
## Task Description

Once the majority of our users has updated to 6.3 and usage of 6.1 has dropped, we can look at increasing our minimum WordPress version requirement again. Maybe around the 6.4 release. This is just a tracking ticket for now.

Such a bump usually allows us to remove some technical debt both on the PHP and JS side of the plugin.

Previously:

* #13413
* #13260

Resources:

* [WordPress 6.2 field guide](https://make.wordpress.org/core/2023/03/09/wordpress-6-2-field-guide/)

Things that stand out:

* Availability of `WP_HTML_Tag_Processor`
* Block editor upgrades to React 18 ⚠️ 
	* That means we probably need to finally update our `@wordpress/` packages to use React 18, and having to manage 2 versions of React in our code base for now — React 18 for WP stuff and React 17 for the editor/dashboard.
	* #13443
* Patched imgAreasSlect jQuery plugin
	* This happened in https://github.com/WordPress/wordpress-develop/commit/ef0c1d1dd28f13bbe6b39447fb5fbc36edf7df80 (https://core.trac.wordpress.org/ticket/54308 / https://core.trac.wordpress.org/ticket/55377)
	* I think this allows us to finally remove our patched version in `packages/imgareaselect` 🎉 

Tasks include:

* [x] Bump in `readme.txt`
* [x] Bump in `web-stories.php` (twice)
* [x] Bump in `tests/phpstan/bootstrap.php` for consistency
* [x] Update `minimum_supported_wp_version` in `phpcs.xml.dist`
* [x] Run e2e tests against 6.2 instead of 6.1
* [x] Run unit tests against 6.2 instead of 6.1
* [x] Re-evaluate PHPUnit matrix and composer dependencies if necessary
* [x] Revert 6749017043569b9c7c77318d804ad5a101ee274a
* [x] Remove `packages/imgareaselect` package

**Comment by swissspidy** [comment]
I don't see a use case for the HTML API in our code base. While we do have some places where we manipulate HTML strings, like in the `Cross_Origin_Isolation` class, doing so with `str_replace` the way we do it is much much faster than using the `WP_HTML_Tag_Processor`. So no change needed there.

**Comment by AnuragVasanwala** [comment]
@swissspidy I have created two PRs which addresses following tasks of this issue:
* [x] Bump in `readme.txt`
* [x] Bump in `web-stories.php` (twice)
* [x] Bump in `tests/phpstan/bootstrap.php` for consistency
* [x] Update `minimum_supported_wp_version` in `phpcs.xml.dist`
* [ ] Run e2e tests against 6.2 instead of 6.1
* [ ] Run unit tests against 6.2 instead of 6.1
* [ ] Re-evaluate PHPUnit matrix and composer dependencies if necessary
* [x] Revert 6749017043569b9c7c77318d804ad5a101ee274a
* [x] Remove `packages/imgareaselect` package

#13474 bumps WP min version to `6.2` and #13473 removes `imgareaselect` patch. Once these PRs are ready, we can start running e2e and unit tests against `6.2`.

**Comment by swissspidy** [comment]
We can and should change the e2e/unit test matrix before #13474, as otherwise tests in that PR fail
