### ISSUE TITLE
WordPress 6.4 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#13447]
## Task Description

According to https://make.wordpress.org/core/6-4/, the first RC will be out in mid-October, with general release in early November.

Here's an article covering what to expect: https://wptavern.com/wordpress-6-4-roadmap-includes-typography-management-features-new-blocks-and-twenty-twenty-four-default-theme

Things that stand out:

* New default theme, Twenty Twenty-Four
* New font library feature
	* We might want to support this for stories.

**Previously:**

* #13043
* #13259

**Before release of WordPress 6.4:**

* [x] Manual testing against trunk/Beta/RC releases
* [x] Run E2E tests against 6.4 RC once published
* [x] Update staging environments to use 6.4 RC
* [x] Bump `Tested up to` in `readme.txt`

**After release of WordPress 6.4:**

* [x] Update `php-stubs/wordpress-stubs` (via `composer update php-stubs/wordpress-stubs`)
* [x] Update `sniccowp/php-scoper-wordpress-excludes`

**Comment by swissspidy** [comment]
> New default theme, Twenty Twenty-Four

We need to ensure that the Web Stories block looks good in TT4. Probably need to update `Core_Themes_Support` and add specific CSS to `packages/stories-block/src/css/core-themes/twentytwentyfour.css`

**Comment by swissspidy** [comment]
Given that the Font Library is tied to the site editor and doesn't provide any filters, we don't really need to be concerned about it. So no action needed.

**Comment by swissspidy** [comment]
Our QA site now runs 6.4 Beta 2 for easier testing

**Comment by AnuragVasanwala** [comment]
> > New default theme, Twenty Twenty-Four
> 
> We need to ensure that the Web Stories block looks good in TT4. Probably need to update `Core_Themes_Support` and add specific CSS to `packages/stories-block/src/css/core-themes/twentytwentyfour.css`

I have verified that Web Stories (v1.34.0) block looks good in TT4 (WordPress 6.4 Beta 2) for all of the available layouts. I think, we may not need to update `Core_Themes_Support` for now. What do you suggest?

**Comment by swissspidy** [comment]
So we don‘t even need any custom CSS specific for that theme?

**Comment by AnuragVasanwala** [comment]
> So we don‘t even need any custom CSS specific for that theme?

Yes, as per UI perspective - it does look good. I didn't discover any issues with block editor so far.

Is there anything else I need to look for? I am trying to understand based on the other available CSS in `packages/stories-block/src/css/core-themes/` directory and previous issues [WordPress 6.2 Compatibility](https://github.com/GoogleForCreators/web-stories-wp/issues/13043) & [WordPress 6.3 Compatibility](https://github.com/GoogleForCreators/web-stories-wp/issues/13259).

Please let me know, if there is something missing.

**Comment by swissspidy** [comment]
Any design issues on the frontend when using the block with TT4?

**Comment by AnuragVasanwala** [comment]
> Any design issues on the frontend when using the block with TT4?

So far, so good. Didn't found any design issues when using Web Stories block with TT4 on frontend. Although, I will make sure to test it out for upcoming Beta releases and will fix if there are any issues.

**Comment by swissspidy** [comment]
> * New font library feature

Note that this has been punted to 6.5
