### ISSUE TITLE
Bump WP version requirement to 6.3+

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#13515]
## Task Description

Once the majority of our users has updated to 6.4 and usage of 6.2 has dropped, we can look at increasing our minimum WordPress version requirement again.

Such a bump usually allows us to remove some technical debt both on the PHP and JS side of the plugin.

Previously:

* #13413
* #13260
* #13424

Resources:

* [WordPress 6.3 Field Guide](https://make.wordpress.org/core/2023/07/18/wordpress-6-3-field-guide/)

Things that stand out:

* [Script strategy support](https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/): use `async` and `defer` for scripts.
	* We should definitely update frontend scripts to use a more appropriate strategy where applicable.
* `WP_DEVELOPMENT_MODE` / `wp_is_development_mode`.
	* Not sure where this would be useful in our plugin. Maybe for disabling AMP sanitization? Otherwise useful for disabling caching etc. but we don't have that.

Tasks include:

* [x] Bump in `readme.txt`
* [x] Bump in `web-stories.php` (twice)
* [x] Bump in `tests/phpstan/bootstrap.php` for consistency
* [x] Update `minimum_supported_wp_version` in `phpcs.xml.dist`
* [x] Run e2e tests against 6.3 instead of 6.2
* [x] Run unit tests against 6.3 instead of 6.2
* [x] Re-evaluate PHPUnit matrix and composer dependencies if necessary
