### ISSUE TITLE
WordPress 6.5 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#13581]
## Task Description

Schedule: https://make.wordpress.org/core/6-5/

RC 1 is planned for March 5, with stable release on March 26.

Things that stand out:

* Native AVIF support (most likely)
* Interactivity API / ES Modules API / import maps
* New i18n library
* Various block editor improvements, with dataviews, block bindings, etc.

**Previously:**

* #13043
* #13259
* #13447

**Before release of WordPress 6.5:**

* [x] Manual testing against trunk/Beta/RC releases
* [x] Run E2E tests against 6.5 RC once published
* [x] Update staging environments to use 6.5 RC
* [x] Bump `Tested up to` in `readme.txt`

**After release of WordPress 6.5:**

* [x] Update `php-stubs/wordpress-stubs` (via `composer update php-stubs/wordpress-stubs`)
* [x] Update `php-stubs/wordpress-tests-stubs`
* [x] Update `sniccowp/php-scoper-wordpress-excludes`
