### ISSUE TITLE
WordPress 6.6 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#13702]
## Task Description

Schedule: https://make.wordpress.org/core/6-6/

Important dates:

* Beta 1 on June 4
* RC1 on June 25
* Stable release on July 16

Things that stand out:

* Potential changes to plugin onboarding/configuration flows

**Previously:**

* #13043
* #13259
* #13447
* #13581

**Before release of WordPress 6.6:**

* [x] Manual testing against trunk/Beta/RC releases
* [x] Run E2E tests against 6.6 RC once published
* [x] Update staging environments to use 6.6 RC
* [x] Bump `Tested up to` in `readme.txt`

**After release of WordPress 6.6:**

* [ ] Update `php-stubs/wordpress-stubs` (via `composer update php-stubs/wordpress-stubs`)
* [x] Update `php-stubs/wordpress-tests-stubs`
* [ ] Update `sniccowp/php-scoper-wordpress-excludes`

**Comment by swissspidy** [comment]
@Swanand01 Once 6.6 RC1 is out next week, we can start with running our e2e tests against it. I'll then also update our QA site and my local dev site for testing.

**Comment by swissspidy** [comment]
Nothing in the [field guide](https://make.wordpress.org/core/2024/06/25/wordpress-6-6-field-guide/) stands out to me
