### ISSUE TITLE
WordPress 6.7 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#13804]
## Task Description

Schedule: https://make.wordpress.org/core/6-7/

Important dates:

* RC1 on October 22
* Stable release on November 12

Things that stand out:

* A bunch of deprecations in the Web Stories block, e.g. "Bottom margin styles for `wp.components.ToggleControl` is deprecated since version 6.7 and will be removed in version 7.0. Note: Set the `__nextHasNoMarginBottom` prop to true to start opting into the new styles, which will become the default in a future version." Same for `RangeControl`, `TextControl`, `SelectControl`, and so on.

**Previously:**

* #13043
* #13259
* #13447
* #13581
* #13702

**Before release of WordPress 6.7:**

* [x] Manual testing against trunk/Beta/RC releases
* [x] Run E2E tests against 6.7 RC once published
* [x] Update staging environments to use 6.6 RC
* [x] Bump `Tested up to` in `readme.txt`

**After release of WordPress 6.7:**

* [x] Update `php-stubs/wordpress-stubs` (via `composer update php-stubs/wordpress-stubs`)
* [x] Update `php-stubs/wordpress-tests-stubs`
* [x] Update `sniccowp/php-scoper-wordpress-excludes`
