### ISSUE TITLE
WordPress 5.9 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9622]
## Task Description

WordPress 5.9 development timeline: https://make.wordpress.org/core/5-9/

5.9 RC 1 is slated for 30 November 2021

5.9 stable is slated for 14 December 2021.

Before release of WordPress 5.9:

* [x] Do some testing against 5.9 Beta releases (#9733)
* [x] Run E2E tests against 5.9 RC once published  
  * [ ] Add test for #9971
* [x] Update staging environments to use 5.9 RC
* [x] Bump `Tested up to` in `readme.txt`
* [ ] Add customizer support for Twenty Twenty-Two

After release of WordPress 5.9:

* [ ] Update `php-stubs/wordpress-stubs` (perhaps submit a PR to update stubs)

Notable things to test:

* Twenty Twenty-Two
* Web Stories block in Full Site Editing

**Comment by spacedmonkey** [comment]
What about compatiblity with the new default theme 2022? 

https://github.com/google/web-stories-wp/blob/03a51f7df190a40c217d02ffec8b5d2863262ef7/includes/Integrations/Core_Themes_Support.php#L45-L57

**Comment by swissspidy** [comment]
Good point 👍

**Comment by swissspidy** [comment]
Proposed schedule shared on Slack:

Nov 30 - Beta 1 (2 weeks from now)
Dec 7 - Beta 2
Dec 14 - Beta 3
Dec 21 - Beta 4 (optional)
Jan 4 - RC 1 (5 weeks from Beta)
Jan 11 - RC2
Jan 18 - RC 3
Jan 25 - Release date

So we might have some more time after all

**Comment by spacedmonkey** [comment]
Should we run E2E, unit tests again WP 5.9 RC1?

**Comment by swissspidy** [comment]
Yes we should run e2e tests against RC1, as also noted in the ticket description. Like we did in #8136
